name: Rewardsy Health Checks

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/10 * * * *'
  workflow_dispatch:

env:
  REWARDSY_BACKEND_URL: https://api.rewardsy.one/rewardsy-backend
  REWARDSY_WEBAPP_URL: https://app.rewardsy.one

jobs:
  rewardsy-backend-health-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.health_check.outcome }}
    steps:
      - name: Check rewardsy-backend health
        id: health_check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.REWARDSY_BACKEND_URL }}/docs/core)
          if [ "$response" -ne 200 ]; then
            echo "Rewardsy backend is down! HTTP status code: $response"
            exit 1
          else
            echo "Rewardsy backend is healthy."
          fi

  rewardsy-webapp-health-check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.health_check.outcome }}
    steps:
      - name: Check rewardsy-webapp health
        id: health_check
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.REWARDSY_WEBAPP_URL }})
          if [ "$response" -ne 200 ]; then
            echo "Rewardsy webapp is down! HTTP status code: $response"
            exit 1
          else
            echo "Rewardsy webapp is healthy."
          fi

  notify-status:
    runs-on: ubuntu-latest
    needs: [rewardsy-backend-health-check, rewardsy-webapp-health-check]
    if: always()
    steps:
      - name: Send Discord Notification for Backend Status
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: https://discord.com/api/webhooks/1391803646500671588/7_zWESR3N1FtkNIu-vsAKdicx8JTjdlBYW0WPLvkr7VK3IaRRefqy2zW7eqEwoDqF5Cx
          status: ${{ needs['rewardsy-backend-health-check'].outputs.status }}
          title: "🚦 Health check status for rewardsy-backend: ${{ needs['rewardsy-backend-health-check'].outputs.status }}"
          description: |
            ${{ needs['rewardsy-backend-health-check'].outputs.status == 'failure' && '@everyone' || '' }} The health check for rewardsy-backend has finished with status: ${{ needs['rewardsy-backend-health-check'].outputs.status }}.
          color: ${{ needs['rewardsy-backend-health-check'].outputs.status == 'success' && 0x00ff00 || 0xff0000 }}
          url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Send Discord Notification for Webapp Status
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: https://discord.com/api/webhooks/1391803646500671588/7_zWESR3N1FtkNIu-vsAKdicx8JTjdlBYW0WPLvkr7VK3IaRRefqy2zW7eqEwoDqF5Cx
          status: ${{ needs['rewardsy-webapp-health-check'].outputs.status }}
          title: "🚦 Health check status for rewardsy-webapp: ${{ needs['rewardsy-webapp-health-check'].outputs.status }}"
          description: |
            ${{ needs['rewardsy-webapp-health-check'].outputs.status == 'failure' && '@everyone' || '' }} The health check for rewardsy-webapp has finished with status: ${{ needs['rewardsy-webapp-health-check'].outputs.status }}.
          color: ${{ needs['rewardsy-webapp-health-check'].outputs.status == 'success' && 0x00ff00 || 0xff0000 }}
          url: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
