name: Check if the build is happening and formatting is correct

env:
  DEV_REWARDSY_BACKEND_NAME: rewardsy-dev-backend

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  spotless-check:
    name: Build and Push Docker Image (PR Check Only)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run format + lint check
        run: npm run spotless:check

  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: spotless-check

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase the repo name and username
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v5
        with:
          push: false
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          file: ./Dockerfile
